apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: honestbee-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: honestbee-deployment
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60